# Introduction to Julia Language

For the implementation of the practice exercises, there are several options in terms of programming language.  Among the many available options, we will consider the following three languages:

* **Matlab** is a scientific programming language with many years of development. It has the advantage of offering a large number of modules (called Toolboxes) for almost any scientific or technical task, along with excellent documentation. This makes it a suitable language for beginners. However, its main disadvantage is that it requires a paid license, which limits its use in many companies. As a result, it is less commonly used than Python in industry.

* **Python** is undoubtedly the most widely used language in data science and machine learning. It is modern and simple, with a vast ecosystem of modules and extensive documentation. Although it doesn't quite match Matlab in terms of scientific features or numerical performance, it is free, open-source, and general-purpose. Notably, key deep learning libraries like TensorFlow and PyTorch were first developed for Python, significantly expanding its community. Other machine learning tools, such as Scikit-learn, also make it a strong option. However, since it is not a scientific language by design, numerical efficiency depends on libraries like NumPy, which introduces performance limitations compared to natively vectorized languages."

* **Julia** is a relatively new scientific programming language developed at MIT. Although its first stable release is only a few years old, it is rapidly evolving. Julia aims to combine the scientific strengths of Matlab with the simplicity and openness of Python, while providing better performance than both. Despite its youth, the number of available packages is growing quickly. However, its community and industry adoption are still smaller compared to Python and Matlab

As has been indicated, it is a language that does not yet have a large presence at the enterprise level, however, this is mitigated by three important factors:

* Having acquired Python language skills in other subjects, this subject provides an opportunity to learn a scientific language that completes the knowledge.

* Several prestigious institutions, such as Berkeley, Stanford, and MIT, recommend and teach Julia due to its fine-grained performance control and suitability for research and experimentation..

* Although Python is the most widely used language at the enterprise level, the Scikit-Learn library is also available in Julia.  Learning Julia in this course also strengthens understanding of libraries like Scikit-learn, which are available in both Julia and Python, enabling students to apply their knowledge seamlessly across both languages.

## Installation

Julia installation is pretty straightforward, whether using precompiled binaries or compiling from source. Download and install Julia by following the instructions at [https://julialang.org/downloads/].

> ⚠️ **Older Mac users**: Installing Julia might be troublesome due to deprecated compilers. In case of errors during installation, it might be worth trying to install it via [MacPorts](https://ports.macports.org/port/julia/). After MacPorts [installation](https://www.macports.org/install.php/), Julia can be installed just by `sudo port install julia`.

It could be worth to also install jupyter in a local environment to perform some test. This can be done by executing the following command, if you do not have it already installed.

To be executed if needed on the terminal, previous to execute any code here:
```bash
        pip install notebook
```

After that installation you can proceed to install the kernel of Julia for jupyter notebook. Simply open a terminal and type `julia`. You should see the following environment 

![Image of the startup of Julia in the terminal](./img/JuliaTerminal.png "Julia Terminal")

To add the support for notebooks to should execute the following lines, which we would cover more indeed on the following lines

```julia
    using Pkg
    Pkg.add("IJulia")
    
```

This lines load the `Pkg` package, which is used to manage packages in Julia. Here, we are adding the `IJulia` package. Once installed, you can run Julia code inside Jupyter notebooks. The next step is to start Jupyter by executing: 
```bash
    jupyter notebook
```
Then, you can access the provided URL in your browser to create new notebooks in both Python and Julia.

Alternatively, you can launch the notebook interface directly from the Julia REPL with:

```julia
    using IJulia
    notebook()
```

In this subject, various Julia packages will be used. Some of them, such as Statistics, are included in the standard distribution and can be used directly with:

In [1]:
using Statistics

If you only need specific functions from a package, you can import them selectively:

In [2]:
using Statistics: mean

Other packages are not included by default and must be installed manually. Below are some of the packages we will be using:: 

* FileIO: General interface for file input/output operations. 
* XLSX: Enables reading data from Excel files. 
* JLD2: Allows saving and loading Julia variables to/from file (depends on FileIO). 
* Flux: Provides tools for training Artificial Neural Networks in Julia.
* MLJ: Julia implementation of machine most renoun machine learning techniques
* ScikitLearn: Julia implementation of the popular Python machine learning library, offering a consistent interface for models and utilities. 
* Plots: General plotting library in Julia. 
* MAT: Enables reading MATLAB `.mat` files. 
* Images: Provides tools for image processing and manipulation. 

The first time they are used, they are pre-compiled. For example, if your data is stored in an Excel file, you can use the `readdata` function from the XLSX package to load it. 

In [3]:
import Pkg; Pkg.add("XLSX");

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`


In [4]:
using XLSX:readdata

## Basic syntax in Julia
This section presents some typical operations with two main objectives: first, to serve as a quick reference or cheatsheet; and second, to verify that the previous setup was successful. Many of the examples are based on this [tutorial](https://learnxinyminutes.com/docs/julia/) that can be used as additional reference. 

### Types of numbers
In Julia, there are several types of numbers. Although during the first practice we will indeep in this question. Here are some examples of different definitions

In [5]:
typeof(2)

Int64

In [6]:
typeof(4.0)

Float64

In [7]:
typeof(1 + 1im)

Complex{Int64}

In [8]:
typeof(2 // 3)

Rational{Int64}

In [9]:
supertype(AbstractFloat)

Real

In [10]:
supertype(Real)

Number

In [11]:
supertype(Number)

Any

### Boolean Operators
Be aware that the negation is performed with `!`

In [12]:
(1==1) & !(1!=1)

true

### Strings

In [13]:
typeof("This is a string")

String

In [14]:
typeof('a') != typeof("a") # the single quote is only for caracters

true

In [15]:
using Printf
Printf.@printf "%d is less than %f" 4.5 5.3

4 is less than 5.300000

In [16]:
println("This is in Julia - $(VERSION)")

This is in Julia - 1.10.0


### Variable
The variable names has to start with a letter, but after that you can use letters, digits, underscores, and exclamation points

In [17]:
xMarksTheSpot2Dig! = 1

1

In [18]:
a = Int64[]

Int64[]

In [19]:
push!(a, 1)

1-element Vector{Int64}:
 1

In [20]:
push!(a, 2)

2-element Vector{Int64}:
 1
 2

In [21]:
b = [3, 4, 5]

3-element Vector{Int64}:
 3
 4
 5

In [22]:
b[1]

3

In [23]:
b[end]

5

In [24]:
append!(a, b)

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [25]:
pop!(a)

5

In [26]:
a[2:3]

2-element Vector{Int64}:
 2
 3

In [27]:
4 in a

true

In [28]:
length(a)

4

### Tuples

In [29]:
a = (1, 5, 3)
typeof(a)

Tuple{Int64, Int64, Int64}

In [30]:
a[2]

5

In [31]:
a, b, c = (1, 2, 3)

(1, 2, 3)

In [32]:
println(" First element is $(a), Second is $(b), and last is $(c)")

 First element is 1, Second is 2, and last is 3


In [33]:
n = (x=1, y=2, z=3) # use keyword assignments in a tuple to create a NamedTuple

(x = 1, y = 2, z = 3)

In [34]:
println(" First element is $(n.x), Second is $(n.y), and last is $(n.z)")

 First element is 1, Second is 2, and last is 3


### Dictionaries

In [35]:
d = Dict("one"=>1, "two"=>2, "three"=>3)

Dict{String, Int64} with 3 entries:
  "two"   => 2
  "one"   => 1
  "three" => 3

In [36]:
d["one"]

1

In [37]:
keys(d)

KeySet for a Dict{String, Int64} with 3 entries. Keys:
  "two"
  "one"
  "three"

In [38]:
values(d)

ValueIterator for a Dict{String, Int64} with 3 entries. Values:
  2
  1
  3

In [39]:
haskey(d, "one")

true

### Control Flow

In [40]:
condition_var = 5

# if-then=else
# Indentation is not meaningful in Julia.

if condition_var > 10
    println("If branch is mandatory")
elseif condition_var < 10    
    println("Elseif branch is optional")
else                    
    println("The else branch os also optional")
end

Elseif branch is optional


In [41]:
# The for loop can work on iterables
for animal in ["dog", "cat", "mouse"]
    println("$animal is a mammal")
    # You can use $ to interpolate variables or expression into strings
end

dog is a mammal
cat is a mammal
mouse is a mammal


In [42]:
for (k,v) in Dict("dog"=>"mammal","cat"=>"mammal","mouse"=>"mammal")
    println("$k is a $v")
end

mouse is a mammal
cat is a mammal
dog is a mammal


In [43]:
# The while loop
x = 0
while x < 4
    global x # be aware that the variable which is changed is the global one
    println(x)
    x += 1  # Shorthand for x = x + 1
end

0
1
2
3


### Functions

In [44]:
# You can define a function with or without defatult values
function defaults(a, b, x=5, y=6)
    return "$a $b and $x $y"
end

defaults (generic function with 3 methods)

In [45]:
defaults('h', 'g', 'j')  # => "h g and j 6"

"h g and j 6"

In [46]:
try
    defaults('h')  # => ERROR: MethodError: no method matching defaults(::Char)
catch e
    println(e)
end

MethodError(defaults, ('h',), 0x0000000000007af9)


In [47]:
function all_the_args(normalArg, optionalPositionalArg=2; keywordArg="foo")
    println("normal arg: $normalArg")
    println("optional arg: $optionalPositionalArg")
    println("keyword arg: $keywordArg")
end

all_the_args("normal")

normal arg: normal
optional arg: 2
keyword arg: foo


In [48]:
# Lambda expressions
(x -> x+1)(3)

4

In [49]:
# Julia has first class functions
function create_adder(x)
    adder = function (y)
        return x + y
    end
    return adder
end

create_adder (generic function with 1 method)

In [50]:
# This function is identical to create_adder implementation above.
function create_adder(x)
    y -> x + y
end

create_adder (generic function with 1 method)

In [51]:
# You can also name the internal function, if you want
function create_adder(x)
    function adder(y)
        x + y
    end
    adder
end

create_adder (generic function with 1 method)

In [52]:
f = create_adder(10)
map(f, [1,2,3])

3-element Vector{Int64}:
 11
 12
 13

In [53]:
filter(x -> x > 5, [3, 4, 5, 6, 7])

2-element Vector{Int64}:
 6
 7

In [54]:
[f(i) for i in [1, 2, 3]]

3-element Vector{Int64}:
 11
 12
 13

### Composite Types
Julia allows you to define new composite types (similar to structs or classes in other languages). These types can be part of a hierarchy, enabling method inheritance and supporting multiple dispatch. 

In [55]:
abstract type Cat end # just a name and point in the type hierarchy
subtypes(Cat)

Any[]

In [56]:
# <: is the subtyping operator
struct Lion <: Cat # Lion is a subtype of Cat
    mane_color
    roar::String
end

struct Panther <: Cat # Panther is also a subtype of Cat
  eye_color
  Panther() = new("green")
  # Panthers will only have this constructor, and no default constructor.
end

# Also it is not required to inheritance anything
struct Tiger
  taillength::Float64
  coatcolor # not including a type annotation is the same as `::Any`
end

subtypes(Cat)

2-element Vector{Any}:
 Lion
 Panther

In [57]:
function voice(animal::Lion)
  animal.roar # access type properties using dot notation
end

function voice(animal::Panther)
  "grrr"
end

function voice(animal::Tiger)
  "rawwwr"
end

voice (generic function with 3 methods)

In [58]:
println("The Tiger says $(voice(Tiger(3.5,"orange")))")
println("The Lion says $(voice(Lion("brown","ROAAAR")))")
println("The Lion says $(voice(Panther()))")

The Tiger says rawwwr
The Lion says ROAAAR
The Lion says grrr


### Native Code

In [59]:
Add(x, y) = x + y

Add (generic function with 1 method)

In [60]:
Add(4,5)

9

In [61]:
code_native(Add, (Int32,Int32), syntax = :intel)

	.text
	.file	"Add"
	.globl	julia_Add_1923                  # -- Begin function julia_Add_1923
	.p2align	4, 0x90
	.type	julia_Add_1923,@function
julia_Add_1923:                         # @julia_Add_1923
; ┌ @ In[59]:1 within `Add`
# %bb.0:                                # %top
	push	rbp
	mov	rbp, rsp
                                        # kill: def $esi killed $esi def $rsi
                                        # kill: def $edi killed $edi def $rdi
; │┌ @ int.jl:87 within `+`
	lea	eax, [rdi + rsi]
; │└
	pop	rbp
	ret
.Lfunc_end0:
	.size	julia_Add_1923, .Lfunc_end0-julia_Add_1923
; └
                                        # -- End function
	.section	".note.GNU-stack","",@progbits


In [62]:
code_native(Add, (Float32,Float32), syntax = :intel)

	.text
	.file	"Add"
	.globl	julia_Add_1946                  # -- Begin function julia_Add_1946
	.p2align	4, 0x90
	.type	julia_Add_1946,@function
julia_Add_1946:                         # @julia_Add_1946
; ┌ @ In[59]:1 within `Add`
# %bb.0:                                # %top
	push	rbp
	mov	rbp, rsp
; │┌ @ float.jl:409 within `+`
	vaddss	xmm0, xmm0, xmm1
; │└
	pop	rbp
	ret
.Lfunc_end0:
	.size	julia_Add_1946, .Lfunc_end0-julia_Add_1946
; └
                                        # -- End function
	.section	".note.GNU-stack","",@progbits


In [63]:
code_llvm(Add, (Int32,Int32))

;  @ In[59]:1 within `Add`
define i32 @julia_Add_1978(i32 signext %0, i32 signext %1) #0 {
top:
; ┌ @ int.jl:87 within `+`
   %2 = add i32 %1, %0
; └
  ret i32 %2
}


## Julia Environments

### What is a Julia environment (a.k.a. project)?

In Julia, an **environment** (also commonly called a **project**) is a workspace that defines its own set of packages and versions.  
This ensures that your code runs with the exact dependencies you specify — independently of what is installed globally or in other projects.

If you're familiar with **Python**, this is very similar to using `venv`, `conda`, or `poetry`.  
In **R**, it's similar to using `renv` or `packrat`.

Environments in Julia are defined by two key files:

- `Project.toml`: lists your direct dependencies.
- `Manifest.toml`: records the exact versions of all packages (including transitive dependencies).

> 📁 Any folder with a `Project.toml` is considered a **Julia project**.

```
 my_project/
 ├── Project.toml
 ├── Manifest.toml
 └── notebook.ipynb
```

---

### 🔄 Comparison with other ecosystems

| Feature                  | **Julia**                          | **Python**                          | **R**                          |
|--------------------------|------------------------------------|-------------------------------------|--------------------------------|
| Environment name         | Environment / Project              | Virtual environment (`venv`, `conda`) | Project / renv environment    |
| Dependency list file     | `Project.toml`                     | `requirements.txt` / `pyproject.toml` | `renv.lock` / `DESCRIPTION`   |
| Full version lock file   | `Manifest.toml`                    | `poetry.lock` / `Pipfile.lock`      | `renv.lock` / `.Rprofile`     |
| Activation               | `Pkg.activate("path")`             | `source venv/bin/activate` or `conda activate` | `renv::activate()`         |
| Install package          | `Pkg.add("PkgName")`               | `pip install PkgName`               | `install.packages("PkgName")` |
| Isolation                | ✔ Per project                      | ✔ Per virtualenv/conda              | ✔ Per project                 |

---

Using environments is essential for:

- Keeping dependencies organized and isolated
- Reproducing your results
- Collaborating safely across different machines or teammates

In the next sections, you'll learn how to create and activate a Julia environment for your notebooks.

### Why use environments in Julia?

In Julia, managing dependencies properly is essential to avoid version conflicts and ensure reproducibility.

By default, when you install a package, it is added to your **global environment**, which is shared across all projects.  
This can lead to incompatibilities when different projects require different versions of the same package.

The recommended solution is to use ***project-specific environments***, which isolate dependencies per notebook or application.

### Creating a new project

You can create a new environment by opening Julia and running the following in the REPL:

```julia
] activate .
] instantiate
```
* `activate .` tells Julia to create or activate a project in the current folder.

* If a `Project.toml` does not exist, it will be created automatically.

* `instantiate` installs the packages listed in Project.toml and Manifest.toml.

📝 It’s a good practice to run your notebooks inside such a folder and activate the environment at the top of the notebook.

### Activating environments in Jupyter notebooks

At the top of your notebook, add the following code:

In [64]:
using Pkg
Pkg.activate(".")

  Activating new project at `~/work`


You only need to activate the environment once per session. After that, any `Pkg.add(...)` call will install packages into this environment only.

### Adding and removing packages

To add a package:

In [ ]:
using Pkg
Pkg.add("Plots")

   Resolving package versions...
   Installed StructUtils ──── v2.5.0
   Installed StatsBase ────── v0.34.6
   Installed DataStructures ─ v0.19.1
   Installed JSON ─────────── v1.0.0
    Updating `~/work/Project.toml`
  [91a5bcdd] + Plots v1.41.1
    Updating `~/work/Manifest.toml`
  [66dad0bd] + AliasTables v1.1.3
  [d1d4a3ce] + BitFlags v0.1.9
  [944b1d66] + CodecZlib v0.7.8
  [35d6a980] + ColorSchemes v3.31.0
  [3da002f7] + ColorTypes v0.12.1
  [c3611d14] + ColorVectorSpace v0.11.0
  [5ae59095] + Colors v0.13.1
  [f0e56b4a] + ConcurrentUtilities v2.5.0
  [d38c429a] + Contour v0.6.3
  [9a962f9c] + DataAPI v1.16.0
  [864edb3b] + DataStructures v0.19.1
  [8bb1440f] + DelimitedFiles v1.9.1
  [ffbed154] + DocStringExtensions v0.9.5
  [460bff9d] + ExceptionUnwrapping v0.1.11
  [c87230d0] + FFMPEG v0.4.4
  [53c48c17] + FixedPointNumbers v0.8.5
  [1fa38f19] + Format v1.3.7
  [28b8d3ca] + GR v0.73.17
  [42e2da0e] + Grisu v1.0.2
  [cd3eb016] + HTTP v1.10.18
  [92d709cd] + IrrationalConstants 

To remove a package:

In [ ]:
Pkg.rm("Plots")

To see all packages:

In [ ]:
Pkg.status()

### Project.toml and Manifest.toml

- `Project.toml` defines which packages and versions your project depends on.
- `Manifest.toml` locks the exact versions, including dependencies of dependencies.

To ensure your environment files are up to date, run the following commands.

```julia
    Pkg.resolve()
    Pkg.precompile()
```

These files should be committed to your Git repository — especially `Project.toml` — to ensure reproducibility for others.

### Tips

- Create a separate environment for each project.
- Always run `Pkg.activate(".")` at the top of your notebook.
- Run `Pkg.instantiate()` after cloning a project to install all required dependencies listed in `Project.toml` and `Manifest.toml`.

## Comandline Integration
To run a Julia script using a specific project environment, use:
```bash
julia --project=. script.jl
```

This will use the Project.toml in the current folder.

## Jupyter Integration
To use your current Julia environment in Jupyter notebooks, you can generate a new Jupyter kernel associated with that environment. Run the following:
```julia
    using IJulia
    IJulia.installkernel("Julia (ML Environment)", env=Base.current_project("relative route to the environment"))
```

Once installed, you’ll see a new kernel named 'Julia (ML Environment)' in Jupyter. Selecting it will automatically use the specified environment — no manual activation needed.

## Suggested Project Structure for Practical Work

To ensure clarity, maintainability, and reproducibility, it is strongly recommended to organise your course projects using a structured folder layout. Here is a suggested directory structure:
```
/ML1/
│
├── environment/ ← Contains the Julia environment files
│ ├── Project.toml
│ └── Manifest.toml
│
├── notebooks/ ← Jupyter notebooks for development and experimentation
│ ├── 00_environment_setup.ipynb
│ └── ... (other notebooks)
│
└── scripts/ ← Julia scripts for reusable or production code
  └── train_model.jl
```


### Why use this structure?

- **Isolation**: All dependencies are managed inside `environment/` to avoid conflicts and ensure reproducibility.
- **Separation of concerns**: Notebooks are used for interactive exploration and documentation; scripts are for finalised or automated code.
- **Portability**: You (and others) can easily clone the repository, activate the environment, and reproduce your results.
- **Scalability**: This layout scales well as your project grows.

### Tips

- Always start your notebooks with (form the notebook folder):
  
  ```julia
      using Pkg
      Pkg.activate("../environment")
  ```
- When running scripts from the command line, use (from the script folder):
  ```bash
      julia --project=environment/ scripts/train_model.jl
  ```

- Alternatively, to use the environment directly in Jupyter, you can generate a dedicated kernel (from the notebook folder):
  ```julia
      using IJulia
      IJulia.installkernel("Julia (ML Environment)", env=Base.current_project("../environment"))
  ```